### ISSUE TITLE
Error: Can't resolve 'ng-intercom'

### ISSUE THREAD

**Issue by marianovf30** [CaliStyle/angular2-intercom#6]
Hello, I am getting this error when i run my app. I am using angular-cli.

Error: "Error: Can't resolve 'ng-intercom'" in app.module"

Error: "Error: Can't resolve 'ng-intercom' in component"

**Comment by wbhob** [comment]
I am aware, it was fixed in 0.2.1

**Comment by marianovf30** [comment]
Thanks for the response. I am using the 0.2.1 version.

**Comment by wbhob** [comment]
Try removing node modules and run npm install

**Comment by marianovf30** [comment]
I just did and get the same error

**Comment by wbhob** [comment]
I know this was an error with 0.1, but I tested and I know it's fixed in 0.2.

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com (https://www.wilsonhobbs.com)
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com (https://www.getcanal.com/)

Twitter/Instagram/Facebook: @getcanal

**Comment by wbhob** [comment]
Make sure angular cli is up to date.

Wilson Hobbs
CEO/Founder/Developer at Canal
11th Grade at The Lovett School

Personal Information
E-mail: wilsonhobbs1@gmail.com
Cell: (404) 719-3252
Website: www.wilsonhobbs.com (https://www.wilsonhobbs.com)
Twitter/Instagram/Facebook: @wbhob

Canal Information
E-mail: wilson@getcanal.com
Web: www.getcanal.com (https://www.getcanal.com/)

Twitter/Instagram/Facebook: @getcanal

**Comment by wbhob** [comment]
I'm going to go ahead and close this, if this is still an issue, please reopen and provide more information (Angular version, CLI version, OS, etc.)

**Comment by otusweb** [comment]
I"m running into the same issue.
HEre is my setup:
```@angular/cli: 1.0.0
node: 6.9.5
os: darwin x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
```

npm view ng-intercom version
``` 0.2.1 ```
